"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { AlertTriangle, BellRing, Bot, CalendarDays, CheckCircle2, Pencil, PiggyBank, Plus, RefreshCcw, ShieldCheck, Target, Wallet2, X } from "lucide-react";
import { createShoppingGoal, getBudgetDashboard, getDealsWebSocketUrl, getMatchedDeals, updateMonthlyBudget, updateShoppingGoal } from "@/lib/api";
import type { BudgetDashboardOut, MatchedDealOut, ShoppingGoalOut } from "@/lib/types";

const categories = ["Tech", "Fashion", "Audio", "Accessories"];
const priorityStyle = { High: "bg-rose-500/10 text-rose-500", Medium: "bg-amber-500/10 text-amber-500", Low: "bg-emerald-500/10 text-emerald-500" } as const;

function MetricCard({ label, value, icon: Icon }: { label: string; value: string; icon: typeof Target }) {
  return <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="glass rounded-xl2 p-4"><div className="flex justify-between"><div><p className="text-[10px] uppercase tracking-wide text-ink-500">{label}</p><p className="mt-2 font-display text-xl font-bold text-ink-100">{value}</p></div><span className="grid h-9 w-9 place-items-center rounded-xl bg-astra-gradient-soft"><Icon className="h-4 w-4 text-astra-cyan" /></span></div></motion.div>;
}

function GoalCard({ goal, busy, onDeposit, onAdjust }: { goal: ShoppingGoalOut; busy: boolean; onDeposit: (amount: number) => void; onAdjust: (price: number) => void }) {
  const [deposit, setDeposit] = useState(""); const [target, setTarget] = useState(String(goal.target_price));
  return <motion.article layout className="glass overflow-hidden rounded-xl2"><div className="relative h-28 bg-base-800">{goal.image_url ? <img src={goal.image_url} alt={goal.target_title} className="h-full w-full object-cover"/> : <div className="grid h-full place-items-center"><Target className="h-8 w-8 text-ink-500"/></div>}<span className={`absolute right-3 top-3 rounded-full px-2 py-1 text-[10px] font-bold ${priorityStyle[goal.priority_level]}`}>{goal.priority_level}</span></div><div className="p-4"><div className="flex items-start justify-between gap-2"><div><h3 className="text-sm font-semibold text-ink-100">{goal.target_title}</h3><p className="mt-1 text-[10px] text-ink-500">{goal.category} · {goal.status}</p></div>{goal.deadline && <span className="flex items-center gap-1 text-[10px] text-ink-500"><CalendarDays className="h-3 w-3"/>{goal.deadline}</span>}</div><div className="mt-4 h-2 overflow-hidden rounded-full bg-base-700"><motion.div initial={{ width: 0 }} animate={{ width: `${goal.percent_funded}%` }} className="h-full rounded-full bg-astra-gradient"/></div><div className="mt-2 flex justify-between text-[10px] text-ink-500"><span>Rs. {goal.saved_amount.toLocaleString()} saved</span><span>{goal.percent_funded}% of Rs. {goal.target_price.toLocaleString()}</span></div><div className="mt-4 grid gap-2 sm:grid-cols-2"><div className="flex gap-1"><input aria-label={`Deposit to ${goal.target_title}`} type="number" min="1" value={deposit} onChange={(e) => setDeposit(e.target.value)} placeholder="Add funds" className="min-w-0 flex-1 rounded-lg border border-base-600 bg-base-800 px-2 py-2 text-[10px] text-ink-100"/><button type="button" disabled={busy || Number(deposit) <= 0} onClick={() => { onDeposit(Number(deposit)); setDeposit(""); }} className="rounded-lg bg-astra-gradient px-2 text-white disabled:opacity-40"><PiggyBank className="h-3.5 w-3.5"/></button></div><div className="flex gap-1"><input aria-label={`Adjust target for ${goal.target_title}`} type="number" min="1" value={target} onChange={(e) => setTarget(e.target.value)} className="min-w-0 flex-1 rounded-lg border border-base-600 bg-base-800 px-2 py-2 text-[10px] text-ink-100"/><button type="button" disabled={busy || Number(target) <= 0 || Number(target) === goal.target_price} onClick={() => onAdjust(Number(target))} className="rounded-lg border border-base-600 px-2 text-ink-300 disabled:opacity-40"><Pencil className="h-3.5 w-3.5"/></button></div></div></div></motion.article>;
}

export default function BudgetAgentDashboard() {
  const [data, setData] = useState<BudgetDashboardOut | null>(null); const [matches, setMatches] = useState<MatchedDealOut[]>([]); const [loading, setLoading] = useState(true); const [busyId, setBusyId] = useState<number | null>(null); const [showCreate, setShowCreate] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const [budgetInput, setBudgetInput] = useState(""); const [editingBudget, setEditingBudget] = useState(false);
  const [title, setTitle] = useState(""); const [price, setPrice] = useState(""); const [category, setCategory] = useState("Tech"); const [priority, setPriority] = useState<"Low"|"Medium"|"High">("Medium"); const [deadline, setDeadline] = useState("");
  const refresh = useCallback(async () => { const [dashboard, matched] = await Promise.all([getBudgetDashboard(), getMatchedDeals()]); setData(dashboard); setMatches(matched); setBudgetInput(String(dashboard.budget.monthly_limit)); }, []);
  useEffect(() => { void refresh().catch((e) => setError(e instanceof Error ? e.message : "Budget Agent could not load.")).finally(() => setLoading(false)); }, [refresh]);
  useEffect(() => {
    let socket: WebSocket | null = null; let retry: number | null = null; let stopped = false;
    const connect = () => {
      socket = new WebSocket(getDealsWebSocketUrl());
      socket.onmessage = (event) => { try { const payload = JSON.parse(event.data) as { type?: string }; if (["budget_alert_created", "deal_updated", "deal_expired"].includes(payload.type ?? "")) void refresh(); } catch {} };
      socket.onclose = () => { if (!stopped) retry = window.setTimeout(connect, 3000); };
    };
    connect();
    return () => { stopped = true; if (retry !== null) window.clearTimeout(retry); socket?.close(); };
  }, [refresh]);
  async function create(event: FormEvent) { event.preventDefault(); if (!title.trim() || Number(price) <= 0) { setError("Target item and max budget are required."); return; } setError(""); try { await createShoppingGoal({ target_title: title.trim(), target_price: Number(price), category, priority_level: priority, deadline: deadline || null }); setTitle(""); setPrice(""); setDeadline(""); setShowCreate(false); setMessage("Goal created and Deal Matcher refreshed."); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : "Goal could not be created."); } }
  async function updateGoal(goalId: number, payload: { deposit_amount?: number; target_price?: number }) { setBusyId(goalId); setError(""); try { await updateShoppingGoal(goalId, payload); setMessage(payload.deposit_amount ? "Funds allocated to goal." : "Goal target updated."); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : "Goal update failed."); } finally { setBusyId(null); } }
  async function saveBudget() { const value = Number(budgetInput); if (value <= 0) { setError("Monthly limit must be greater than zero."); return; } try { setData(await updateMonthlyBudget({ monthly_limit: value })); setEditingBudget(false); setMessage("Monthly budget updated."); setMatches(await getMatchedDeals()); } catch (e) { setError(e instanceof Error ? e.message : "Budget update failed."); } }
  if (loading || !data) return <div className="grid min-h-72 place-items-center"><Bot className="h-8 w-8 animate-pulse text-astra-violet"/></div>;
  const budget = data.budget;
  const savingPlan = data.saving_plan;
  return <div className="space-y-6"><section className="glass rounded-xl2 p-5"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex items-center gap-2"><Wallet2 className="h-5 w-5 text-astra-cyan"/><h2 className="font-display text-lg font-semibold text-ink-100">Monthly Budget</h2></div><p className="mt-2 font-display text-3xl font-bold text-ink-100">Rs. {budget.current_spent.toLocaleString()} <span className="text-sm font-medium text-ink-500">/ Rs. {budget.monthly_limit.toLocaleString()}</span></p></div><div className="w-full max-w-xl"><div className="mb-2 flex justify-between text-[10px] text-ink-500"><span>{budget.spending_percent}% used</span><span>Rs. {budget.available_safe_balance.toLocaleString()} safe balance</span></div><div className="h-3 overflow-hidden rounded-full bg-base-700"><motion.div initial={{ width: 0 }} animate={{ width: `${budget.spending_percent}%` }} className={`h-full rounded-full ${budget.spending_percent >= 90 ? "bg-rose-500" : "bg-astra-gradient"}`}/></div><div className="mt-3 flex justify-end gap-2">{editingBudget ? <><input type="number" value={budgetInput} onChange={(e) => setBudgetInput(e.target.value)} className="w-32 rounded-lg border border-base-600 bg-base-800 px-3 py-2 text-xs text-ink-100"/><button type="button" onClick={() => void saveBudget()} className="rounded-lg bg-astra-gradient px-3 text-xs font-semibold text-white">Save</button><button type="button" onClick={() => setEditingBudget(false)} className="text-xs text-ink-500">Cancel</button></> : <button type="button" onClick={() => setEditingBudget(true)} className="flex items-center gap-1 text-xs text-ink-500"><Pencil className="h-3 w-3"/>Adjust monthly limit</button>}</div></div></div></section>
    <div className="grid gap-4 sm:grid-cols-3"><MetricCard label="Active Goals" value={String(budget.active_goals)} icon={Target}/><MetricCard label="Total Savings via AI Deals" value={`Rs. ${budget.total_ai_deal_savings.toLocaleString()}`} icon={ShieldCheck}/><MetricCard label="Available Safe Balance" value={`Rs. ${budget.available_safe_balance.toLocaleString()}`} icon={Wallet2}/></div>
    {savingPlan && savingPlan.remaining_goal_amount > 0 && <section className="glass rounded-xl2 p-5"><div className="flex flex-wrap items-center justify-between gap-2"><div className="flex items-center gap-2"><PiggyBank className="h-4 w-4 text-astra-cyan"/><h2 className="text-sm font-semibold text-ink-100">Saving Planner</h2></div>{savingPlan.estimated_months_to_fund !== null && <span className="rounded-full bg-astra-gradient-soft px-2.5 py-1 text-[10px] font-bold text-astra-violet">{savingPlan.estimated_months_to_fund} month{savingPlan.estimated_months_to_fund === 1 ? "" : "s"} to fund</span>}</div>{savingPlan.monthly_saving_capacity > 0 ? <div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-astra-cyan/20 bg-astra-cyan/5 p-3"><p className="text-[10px] uppercase tracking-wide text-ink-500">Set aside this month</p><p className="mt-1 text-lg font-bold text-ink-100">Rs. {savingPlan.recommended_monthly_deposit.toLocaleString()}</p></div><div className="rounded-xl border border-base-600 bg-base-800/50 p-3"><p className="text-[10px] uppercase tracking-wide text-ink-500">Still needed for goals</p><p className="mt-1 text-lg font-bold text-ink-100">Rs. {savingPlan.remaining_goal_amount.toLocaleString()}</p></div></div> : <p className="mt-3 rounded-xl bg-amber-500/10 p-3 text-xs text-amber-500">No budget space is available yet. Reduce spending or raise your monthly limit to start this plan.</p>}</section>}
    {(data.restock_forecasts?.length ?? 0) > 0 && <section className="glass rounded-xl2 p-5"><div className="flex flex-wrap items-center justify-between gap-2"><div className="flex items-center gap-2"><RefreshCcw className="h-4 w-4 text-astra-cyan"/><h2 className="text-sm font-semibold text-ink-100">Predictive Restock Alerts</h2></div><span className="rounded-full bg-astra-gradient-soft px-2.5 py-1 text-[10px] font-bold text-astra-violet">AI purchase-interval engine</span></div><p className="mt-1 text-[10px] text-ink-500">ASTRA learns your repurchase rhythm and warns you before you run out.</p><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data.restock_forecasts!.map((forecast, index) => <div key={`${forecast.product_id ?? forecast.product_name}-${index}`} className="rounded-xl border border-base-600 bg-base-800/50 p-3"><div className="flex items-start gap-3">{forecast.image && <img src={forecast.image} alt={forecast.product_name} className="h-12 w-12 rounded-lg object-cover"/>}<div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold text-ink-100">{forecast.product_name}</p><p className="mt-0.5 text-[10px] text-ink-500">{[forecast.category, forecast.last_purchased ? `last bought ${new Date(forecast.last_purchased).toLocaleDateString()}` : null].filter(Boolean).join(" · ")}</p></div><span className="shrink-0 rounded-full bg-emerald-500/10 px-2 py-0.5 text-[9px] font-bold text-emerald-500">{forecast.confidence}% conf.</span></div><div className="mt-3 flex items-center justify-between text-[10px]"><span className="flex items-center gap-1 text-ink-300"><CalendarDays className="h-3 w-3 text-astra-cyan"/> Restock by {new Date(forecast.predicted_next_date).toLocaleDateString()}</span><span className={`font-bold ${forecast.days_until_restock <= 7 ? "text-amber-500" : "text-ink-500"}`}>{forecast.days_until_restock}d left</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-base-700"><div className={`h-full rounded-full ${forecast.days_until_restock <= 7 ? "bg-amber-500" : "bg-astra-gradient"}`} style={{ width: `${Math.max(6, 100 - Math.min(100, forecast.days_until_restock))}%` }}/></div><p className="mt-2 text-[10px] leading-relaxed text-ink-500">{forecast.message} · every ~{forecast.avg_interval_days} days · est. Rs. {Math.round(forecast.estimated_price).toLocaleString()}</p></div>)}</div></section>}
    {(message || error) && <p role="status" className={`rounded-xl p-3 text-xs ${error ? "bg-rose-500/10 text-rose-500" : "bg-emerald-500/10 text-emerald-500"}`}>{error || message}</p>}
    <div className="flex items-center justify-between"><div><h2 className="font-display text-lg font-semibold text-ink-100">Shopping Goals</h2><p className="text-xs text-ink-500">Fund targets and let ASTRA match verified deals automatically.</p></div><button type="button" onClick={() => setShowCreate(true)} className="flex items-center gap-2 rounded-xl bg-astra-gradient px-4 py-2.5 text-xs font-semibold text-white"><Plus className="h-4 w-4"/>Create New Goal</button></div>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data.goals.map((goal) => <GoalCard key={goal.goal_id} goal={goal} busy={busyId === goal.goal_id} onDeposit={(amount) => void updateGoal(goal.goal_id, { deposit_amount: amount })} onAdjust={(target_price) => void updateGoal(goal.goal_id, { target_price })}/>)}{data.goals.length === 0 && <div className="glass col-span-full p-8 text-center text-xs text-ink-500">No shopping goals yet.</div>}</div>
    <div className="grid gap-6 xl:grid-cols-2"><section className="glass rounded-xl2 p-5"><div className="flex items-center gap-2"><Bot className="h-4 w-4 text-astra-violet"/><h2 className="text-sm font-semibold text-ink-100">Budget Guardrail</h2></div><div className="mt-4 space-y-3">{data.alerts.slice(0,8).map((alert) => <div key={alert.alert_id} className="flex gap-3 rounded-xl bg-base-800 p-3">{alert.alert_type === "Budget_Warning" ? <AlertTriangle className="h-4 w-4 shrink-0 text-amber-500"/> : <BellRing className="h-4 w-4 shrink-0 text-emerald-500"/>}<div><p className="text-xs text-ink-300">{alert.message}</p><p className="mt-1 text-[9px] text-ink-500">{new Date(alert.created_at).toLocaleString()}</p></div></div>)}{data.alerts.length === 0 && <p className="text-xs text-ink-500">No alerts yet. ASTRA is monitoring verified deals.</p>}</div></section><section className="glass rounded-xl2 p-5"><div className="flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-emerald-500"/><h2 className="text-sm font-semibold text-ink-100">Verified Goal Matches</h2></div><div className="mt-4 space-y-3">{matches.slice(0,6).map((match) => <div key={`${match.goal_id}-${match.deal_id}`} className="rounded-xl border border-base-600 bg-base-800/50 p-3"><div className="flex gap-3"><img src={match.image} alt={match.product_name} className="h-14 w-14 rounded-lg object-cover"/><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><p className="truncate text-xs font-semibold text-ink-100">{match.product_name}</p><span className="text-[10px] font-semibold text-emerald-500">Trust {match.trust_score}</span></div><p className="mt-1 text-[10px] text-ink-500">Rs. {match.listing_price.toLocaleString()} · Save Rs. {match.savings_vs_target.toLocaleString()}</p>{!match.within_monthly_budget && <p className="mt-1 text-[10px] text-amber-500">Guardrail: suggested Rs. {match.suggested_installment?.toLocaleString()} installment</p>}</div></div><Link href={`/deals?deal=${match.deal_id}&goal=${match.goal_id}`} className="mt-3 flex w-full items-center justify-center rounded-lg bg-astra-gradient py-2 text-[11px] font-semibold text-white">{match.can_buy_with_allocated_savings ? "Buy with Allocated Goal Savings" : "Open Verified Deal"}</Link></div>)}{matches.length === 0 && <p className="text-xs text-ink-500">No high-trust deals match active goals yet.</p>}</div></section></div>
    <AnimatePresence>{showCreate && <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-50 grid place-items-center bg-slate-950/70 p-4 backdrop-blur-sm" onMouseDown={(e) => { if (e.target === e.currentTarget) setShowCreate(false); }}><motion.form initial={{ scale: .96, y: 15 }} animate={{ scale: 1, y: 0 }} onSubmit={create} className="w-full max-w-lg rounded-xl2 border border-base-600 bg-base-950 p-5 shadow-2xl"><div className="flex items-center justify-between"><h2 className="font-display text-lg font-semibold text-ink-100">Create New Goal</h2><button type="button" onClick={() => setShowCreate(false)}><X className="h-5 w-5 text-ink-500"/></button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2 text-xs text-ink-500">Target item<input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Samsung Galaxy S25 Ultra" className="mt-1 w-full rounded-lg border border-base-600 bg-base-800 px-3 py-2.5 text-xs text-ink-100"/></label><label className="text-xs text-ink-500">Max budget<input type="number" min="1" value={price} onChange={(e) => setPrice(e.target.value)} className="mt-1 w-full rounded-lg border border-base-600 bg-base-800 px-3 py-2.5 text-xs text-ink-100"/></label><label className="text-xs text-ink-500">Category<select value={category} onChange={(e) => setCategory(e.target.value)} className="mt-1 w-full rounded-lg border border-base-600 bg-base-800 px-3 py-2.5 text-xs text-ink-100">{categories.map((item) => <option key={item}>{item}</option>)}</select></label><label className="text-xs text-ink-500">Priority<select value={priority} onChange={(e) => setPriority(e.target.value as typeof priority)} className="mt-1 w-full rounded-lg border border-base-600 bg-base-800 px-3 py-2.5 text-xs text-ink-100"><option>Low</option><option>Medium</option><option>High</option></select></label><label className="text-xs text-ink-500">Deadline<input type="date" value={deadline} onChange={(e) => setDeadline(e.target.value)} className="mt-1 w-full rounded-lg border border-base-600 bg-base-800 px-3 py-2.5 text-xs text-ink-100"/></label></div><button type="submit" className="mt-5 w-full rounded-xl bg-astra-gradient py-3 text-xs font-semibold text-white">Create Goal & Start Matching</button></motion.form></motion.div>}</AnimatePresence>
  </div>;
}
