"use client";
import { FormEvent, useEffect, useState } from "react";
import { createSellerInventory, deleteSellerInventory, getSellerInventory, updateSellerInventory, type SellerInventoryItem } from "@/lib/api";
import { Plus, Save, Trash2 } from "lucide-react";

export default function SellerInventoryForm() {
  const [items, setItems] = useState<SellerInventoryItem[]>([]); const [error, setError] = useState("");
  const [form, setForm] = useState({ title: "", category: "Mobiles", price: "", stock_count: "" });
  const load = () => getSellerInventory().then(setItems).catch((e) => setError(e.message));
  useEffect(() => { void load(); }, []);
  async function create(event: FormEvent) { event.preventDefault(); setError(""); try { await createSellerInventory({ ...form, price: Number(form.price), stock_count: Number(form.stock_count) }); setForm({ title: "", category: "Mobiles", price: "", stock_count: "" }); load(); } catch (e) { setError((e as Error).message); } }
  async function edit(item: SellerInventoryItem, field: "price" | "stock_count", value: number) { await updateSellerInventory(item.id, { [field]: value }); load(); }
  async function remove(id: string) { try { await deleteSellerInventory(id); load(); } catch (e) { setError((e as Error).message); } }
  return <section className="glass rounded-xl2 p-5"><h2 className="font-display text-base font-bold text-ink-100">Inventory Management</h2><form onSubmit={create} className="mt-4 grid gap-2 md:grid-cols-5"><input aria-label="Product title" required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Product title" className="rounded-lg bg-base-800 px-3 py-2 text-xs text-ink-100"/><input aria-label="Category" required value={form.category} onChange={e=>setForm({...form,category:e.target.value})} placeholder="Category" className="rounded-lg bg-base-800 px-3 py-2 text-xs text-ink-100"/><input aria-label="Price" required type="number" min="1" value={form.price} onChange={e=>setForm({...form,price:e.target.value})} placeholder="Price" className="rounded-lg bg-base-800 px-3 py-2 text-xs text-ink-100"/><input aria-label="Stock" required type="number" min="0" value={form.stock_count} onChange={e=>setForm({...form,stock_count:e.target.value})} placeholder="Stock" className="rounded-lg bg-base-800 px-3 py-2 text-xs text-ink-100"/><button className="flex items-center justify-center gap-2 rounded-lg bg-astra-gradient px-3 text-xs font-bold text-white"><Plus className="h-4 w-4"/>Create</button></form>{error&&<p className="mt-3 text-xs text-rose-400">{error}</p>}<div className="mt-5 overflow-x-auto"><table className="w-full text-left text-xs"><thead className="text-ink-500"><tr><th className="p-2">Product</th><th>Price</th><th>Stock</th><th>Status</th><th>Actions</th></tr></thead><tbody>{items.map(item=><tr key={item.id} className="border-t border-base-600"><td className="p-2 font-semibold text-ink-100">{item.title}<span className="block text-[10px] text-ink-500">{item.category}</span></td><td><input aria-label={`Price for ${item.title}`} type="number" defaultValue={item.price} onBlur={e=>void edit(item,"price",Number(e.target.value))} className="w-24 rounded bg-base-800 p-2 text-ink-100"/></td><td><input aria-label={`Stock for ${item.title}`} type="number" defaultValue={item.stock_count} onBlur={e=>void edit(item,"stock_count",Number(e.target.value))} className="w-20 rounded bg-base-800 p-2 text-ink-100"/></td><td className={item.stock_count?"text-emerald-400":"text-rose-400"}>{item.status.replaceAll("_"," ")}</td><td><button title="Save price/stock by leaving field" className="mr-2 text-astra-cyan"><Save className="h-4 w-4"/></button><button aria-label={`Delete ${item.title}`} onClick={()=>void remove(item.id)} className="text-rose-400"><Trash2 className="h-4 w-4"/></button></td></tr>)}</tbody></table></div></section>;
}
