"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { Bell, CheckCheck, PackageCheck, Sparkles, Trash2, WalletCards } from "lucide-react";
import PageShell from "@/components/PageShell";
import { clearNotifications, getNotifications, getNotificationsWebSocketUrl, markNotificationRead } from "@/lib/api";
import type { AstraNotification, NotificationCategory } from "@/lib/types";

type Tab = "all" | NotificationCategory;
const tabs: Array<{ key: Tab; label: string }> = [{ key: "all", label: "All" }, { key: "deal_match", label: "Deal Matches" }, { key: "order_update", label: "Order Updates" }, { key: "financial_alert", label: "Financial Alerts" }];
const visuals = { deal_match: { icon: Sparkles, color: "text-violet-400 bg-violet-500/10" }, order_update: { icon: PackageCheck, color: "text-cyan-400 bg-cyan-500/10" }, financial_alert: { icon: WalletCards, color: "text-amber-400 bg-amber-500/10" } };

export default function NotificationsPage() {
  const [items, setItems] = useState<AstraNotification[]>([]); const [tab, setTab] = useState<Tab>("all"); const [loading, setLoading] = useState(true); const [live, setLive] = useState(false);
  const refresh = useCallback(() => getNotifications().then((data) => setItems(data.items)), []);
  useEffect(() => { void refresh().finally(() => setLoading(false)); }, [refresh]);
  useEffect(() => { let retry = 0; let socket: WebSocket | null = null; let stopped = false; const connect = () => { socket = new WebSocket(getNotificationsWebSocketUrl()); socket.onopen = () => setLive(true); socket.onmessage = (event) => { const data = JSON.parse(event.data) as { type?: string }; if (data.type !== "pong" && data.type !== "connected") void refresh(); }; socket.onclose = () => { setLive(false); if (!stopped) retry = window.setTimeout(connect, 3000); }; }; connect(); const ping = window.setInterval(() => socket?.readyState === WebSocket.OPEN && socket.send("ping"), 20000); return () => { stopped = true; clearTimeout(retry); clearInterval(ping); socket?.close(); }; }, [refresh]);
  const visible = useMemo(() => tab === "all" ? items : items.filter((item) => item.category === tab), [items, tab]);
  async function read(item: AstraNotification) { if (!item.is_read) { await markNotificationRead(item.id); setItems((all) => all.map((n) => n.id === item.id ? { ...n, is_read: true } : n)); } }
  async function clear() { await clearNotifications(); setItems([]); }
  return <PageShell active="Notifications" title="Notification Center" subtitle="AI deal matches, order tracking, and wallet safety alerts in one live feed."><section className="glass overflow-hidden rounded-xl2"><div className="flex flex-col gap-4 border-b border-base-600 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="scroll-thin flex gap-1 overflow-x-auto">{tabs.map((item) => <button key={item.key} onClick={() => setTab(item.key)} className={`whitespace-nowrap rounded-full px-4 py-2 text-[11px] font-semibold ${tab === item.key ? "bg-astra-gradient text-white" : "text-ink-500 hover:bg-base-800"}`}>{item.label}</button>)}</div><div className="flex items-center gap-3"><span className={`flex items-center gap-1 text-[10px] ${live ? "text-emerald-400" : "text-ink-700"}`}><i className={`h-2 w-2 rounded-full ${live ? "animate-pulse bg-emerald-400" : "bg-ink-700"}`} /> {live ? "Live" : "Connecting"}</span><button onClick={() => void clear()} disabled={!items.length} className="flex items-center gap-1 text-[10px] font-semibold text-rose-400 disabled:opacity-40"><Trash2 className="h-3 w-3" /> Clear all</button></div></div><div className="p-4">{loading && <p className="p-6 text-center text-xs text-ink-500">Loading notifications…</p>}<AnimatePresence mode="popLayout">{visible.map((item) => { const visual = visuals[item.category]; const Icon = visual.icon; const content = <motion.article layout initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, x: 20 }} onClick={() => void read(item)} className={`mb-2 flex cursor-pointer items-start gap-3 rounded-2xl border p-4 transition ${item.is_read ? "border-base-600 bg-base-900/35" : "border-violet-400/20 bg-violet-500/5"}`}><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl ${visual.color}`}><Icon className="h-4 w-4" /></span><span className="min-w-0 flex-1"><span className="flex items-start justify-between gap-3"><strong className="text-xs text-ink-100">{item.title}</strong>{!item.is_read && <i className="mt-1 h-2 w-2 shrink-0 rounded-full bg-violet-400" />}</span><span className="mt-1 block text-xs leading-5 text-ink-500">{item.message}</span><span className="mt-2 block text-[9px] text-ink-700">{new Date(item.created_at).toLocaleString()}</span></span>{!item.is_read && <button aria-label="Mark as read" className="rounded-full p-1 text-ink-500 hover:text-emerald-400"><CheckCheck className="h-4 w-4" /></button>}</motion.article>; return item.href ? <Link key={item.id} href={item.href}>{content}</Link> : <div key={item.id}>{content}</div>; })}</AnimatePresence>{!loading && visible.length === 0 && <div className="grid place-items-center py-16 text-center"><Bell className="h-7 w-7 text-ink-700" /><p className="mt-3 text-sm font-semibold text-ink-300">You’re all caught up</p><p className="mt-1 text-xs text-ink-700">New Astra alerts will arrive here instantly.</p></div>}</div></section></PageShell>;
}
