"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { motion } from "framer-motion";
import { Activity, AlertTriangle, BadgeCheck, BarChart3, CheckCircle2, Flag, Gauge, ScanSearch, ShieldCheck, Store, Users } from "lucide-react";
import { applyTrustAction, getAstraCheckDashboardStats, inspectTrust } from "@/lib/api";
import type { AstraCheckDashboardStats, TrustInspection } from "@/lib/types";

type Tab = "seller" | "price" | "sentiment";
const tabs: Array<{ key: Tab; label: string }> = [{ key: "seller", label: "Seller Verification" }, { key: "price", label: "Price Integrity" }, { key: "sentiment", label: "AI Sentiment Analysis" }];

function ScoreGauge({ score }: { score: number }) {
  const color = score >= 80 ? "#10b981" : score >= 60 ? "#f59e0b" : "#ef4444";
  const circumference = 2 * Math.PI * 54;
  return <div className="relative mx-auto h-40 w-40"><svg viewBox="0 0 128 128" className="-rotate-90"><circle cx="64" cy="64" r="54" fill="none" stroke="rgb(var(--base-600))" strokeWidth="10" /><motion.circle cx="64" cy="64" r="54" fill="none" stroke={color} strokeWidth="10" strokeLinecap="round" strokeDasharray={circumference} initial={{ strokeDashoffset: circumference }} animate={{ strokeDashoffset: circumference * (1 - score / 100) }} transition={{ duration: .8 }} /></svg><div className="absolute inset-0 grid place-items-center text-center"><div><p className="font-display text-4xl font-bold text-ink-100">{Math.round(score)}</p><p className="text-[10px] uppercase tracking-widest" style={{ color }}>{score >= 80 ? "Safe" : score >= 60 ? "Caution" : "Flagged"}</p></div></div></div>;
}

function Metric({ icon: Icon, label, value }: { icon: typeof Users; label: string; value: string | number }) {
  return <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="glass rounded-xl2 p-4"><div className="flex items-start justify-between"><div><p className="text-[10px] uppercase tracking-wide text-ink-500">{label}</p><p className="mt-2 font-display text-2xl font-bold text-ink-100">{value}</p></div><span className="grid h-9 w-9 place-items-center rounded-xl bg-astra-gradient-soft"><Icon className="h-4 w-4 text-astra-cyan" /></span></div></motion.div>;
}

function PriceGraph({ inspection }: { inspection: TrustInspection }) {
  const points = inspection.price_history.length ? inspection.price_history : [{ label: "Now", market_average: inspection.market_average, current_price: inspection.current_price, observed_at: inspection.inspected_at }];
  const values = points.flatMap((point) => [point.market_average, point.current_price]); const min = Math.min(...values) * .96; const max = Math.max(...values) * 1.04;
  const xy = (value: number, index: number) => `${points.length === 1 ? 50 : index * 100 / (points.length - 1)},${82 - ((value - min) / (max - min || 1)) * 65}`;
  return <div><svg viewBox="0 0 100 90" className="h-48 w-full"><polyline points={points.map((p, i) => xy(p.market_average, i)).join(" ")} fill="none" stroke="#94a3b8" strokeDasharray="3 3" strokeWidth="1.5"/><motion.polyline points={points.map((p, i) => xy(p.current_price, i)).join(" ")} fill="none" stroke="#8b5cf6" strokeWidth="2.5" initial={{ pathLength: 0 }} animate={{ pathLength: 1 }}/></svg><div className="flex justify-between text-[10px] text-ink-500"><span>Current: Rs. {inspection.current_price.toLocaleString()}</span><span>30-day avg: Rs. {inspection.market_average.toLocaleString()}</span></div></div>;
}

export default function AstraCheckDashboard() {
  const [stats, setStats] = useState<AstraCheckDashboardStats | null>(null); const [inspection, setInspection] = useState<TrustInspection | null>(null);
  const [query, setQuery] = useState("samsung-galaxy-s25-ultra"); const [tab, setTab] = useState<Tab>("seller"); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const [messageTone, setMessageTone] = useState<"success" | "error" | "info">("info");
  const [overrideScore, setOverrideScore] = useState("75");
  const [actionReason, setActionReason] = useState("Reviewed by ASTRA trust operations");
  useEffect(() => {
    void Promise.all([getAstraCheckDashboardStats(), inspectTrust("samsung-galaxy-s25-ultra")])
      .then(([nextStats, nextInspection]) => { setStats(nextStats); setInspection(nextInspection); })
      .catch((e) => { setMessageTone("error"); setMessage(e instanceof Error ? e.message : "ASTRA Check could not load."); });
  }, []);
  const metrics = useMemo(() => stats ? [{ icon: Users, label: "Total Verified Sellers", value: stats.total_verified_sellers }, { icon: Flag, label: "Flagged Listings", value: stats.flagged_listings }, { icon: Gauge, label: "Average Platform Trust Index", value: stats.average_platform_trust_index }, { icon: Activity, label: "Real-Time Scans Active", value: stats.real_time_scans_active }] : [], [stats]);
  async function scan(event?: FormEvent) { event?.preventDefault(); if (!query.trim()) return; setBusy(true); setMessage(""); try { setInspection(await inspectTrust(query)); setMessageTone("success"); setMessage("Live audit completed and written to the trust audit log."); setStats(await getAstraCheckDashboardStats()); } catch (e) { setMessageTone("error"); setMessage(e instanceof Error ? e.message : "Inspection failed"); } finally { setBusy(false); } }
  async function action(kind: "manual_override" | "flagged" | "approved_for_deals") {
    if (!inspection) return;
    const score = Number(overrideScore);
    if (!actionReason.trim() || (kind === "manual_override" && (!Number.isFinite(score) || score < 0 || score > 100))) { setMessageTone("error"); setMessage("Enter a reason and a valid score from 0 to 100."); return; }
    setBusy(true); setMessage("");
    try {
      const result = await applyTrustAction(kind, { product_id: inspection.product_id, reason: actionReason.trim(), ...(kind === "manual_override" ? { score } : {}) });
      setInspection((current) => current ? { ...current, trust_score: result.trust_score, risk_level: result.trust_score >= 80 ? "safe" : result.trust_score >= 60 ? "caution" : "flagged", deal_eligible: result.deal_active, authenticity_flag: kind === "flagged" ? true : kind === "approved_for_deals" ? false : current.authenticity_flag, seller: { ...current.seller, is_flagged: kind === "flagged" ? true : kind === "approved_for_deals" ? false : current.seller.is_flagged } } : current);
      setMessageTone("success"); setMessage(`${result.message}. Audit trail saved successfully.`); setStats(await getAstraCheckDashboardStats());
    } catch (e) { setMessageTone("error"); setMessage(e instanceof Error ? e.message : "Action failed"); } finally { setBusy(false); }
  }
  return <div className="space-y-6">
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map((metric) => <Metric key={metric.label} {...metric} />)}{!stats && [1,2,3,4].map((i) => <div key={i} className="h-28 animate-pulse rounded-xl2 bg-base-800" />)}</div>
    <section className="glass rounded-xl2 p-5 lg:p-6"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="flex items-center gap-2 text-sm font-semibold text-ink-100"><ScanSearch className="h-4 w-4 text-astra-cyan"/> Inspection Hub</p><p className="mt-1 text-xs text-ink-500">Enter a Product ID, product name, or exact seller name.</p></div><form onSubmit={scan} className="flex w-full max-w-2xl gap-2"><input value={query} onChange={(e) => setQuery(e.target.value)} className="min-w-0 flex-1 rounded-xl border border-base-600 bg-base-800 px-4 py-3 text-xs text-ink-100 outline-none focus:border-astra-indigo" placeholder="Product ID or Seller Name" aria-label="Product ID or Seller Name"/><button type="submit" disabled={busy || !query.trim()} className="rounded-xl bg-astra-gradient px-5 py-3 text-xs font-semibold text-white disabled:cursor-not-allowed disabled:opacity-50">{busy ? "Processing…" : "Run Live Audit"}</button></form></div>{message && <p role="status" className={`mt-3 rounded-lg p-3 text-xs ${messageTone === "success" ? "bg-emerald-500/10 text-emerald-500" : messageTone === "error" ? "bg-rose-500/10 text-rose-500" : "bg-base-800 text-ink-300"}`}>{message}</p>}</section>
    {inspection ? <div className="grid gap-6 xl:grid-cols-[320px_1fr]"><section className="glass rounded-xl2 p-5 text-center"><ScoreGauge score={inspection.trust_score}/><h2 className="mt-3 font-display text-lg font-semibold text-ink-100">{inspection.product_name}</h2><p className="mt-1 text-xs text-ink-500">{inspection.product_id}</p>{inspection.price_anomaly_detected && <p className="mt-3 rounded-lg bg-rose-500/10 p-2 text-[10px] font-semibold text-rose-500">Price_Anomaly_Warning · 15 point penalty applied</p>}<div className="mt-4 grid grid-cols-3 gap-2 text-[10px]"><div className="rounded-lg bg-base-800 p-2"><p className="text-ink-500">Seller 40%</p><p className="mt-1 font-mono text-ink-100">{inspection.seller_score}</p></div><div className="rounded-lg bg-base-800 p-2"><p className="text-ink-500">Reviews 40%</p><p className="mt-1 font-mono text-ink-100">{inspection.review_sentiment_score}</p></div><div className="rounded-lg bg-base-800 p-2"><p className="text-ink-500">Price 20%</p><p className="mt-1 font-mono text-ink-100">{inspection.price_stability_score}</p></div></div><p className={`mt-4 rounded-lg p-2 text-xs font-semibold ${inspection.deal_eligible ? "bg-emerald-500/10 text-emerald-500" : "bg-rose-500/10 text-rose-500"}`}>{inspection.deal_eligible ? "Eligible for Deals" : "Not active on Deals"}</p></section>
      <section className="glass rounded-xl2 p-5"><div className="scroll-thin flex gap-2 overflow-x-auto border-b border-base-600 pb-3">{tabs.map((item) => <button key={item.key} onClick={() => setTab(item.key)} className={`whitespace-nowrap rounded-lg px-3 py-2 text-xs font-semibold ${tab === item.key ? "bg-astra-gradient text-white" : "text-ink-500"}`}>{item.label}</button>)}</div><div className="mt-5 min-h-56">{tab === "seller" && <div className="grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-base-800 p-4"><Store className="h-4 w-4 text-astra-cyan"/><p className="mt-2 text-xs text-ink-500">Business credentials</p><p className="mt-1 font-semibold text-ink-100">{inspection.seller.business_name} · {inspection.seller.verification_status}</p></div><div className="rounded-xl bg-base-800 p-4"><BadgeCheck className="h-4 w-4 text-emerald-500"/><p className="mt-2 text-xs text-ink-500">Order completion</p><p className="mt-1 font-semibold text-ink-100">{inspection.seller.fulfillment_rate}%</p></div><div className="rounded-xl bg-base-800 p-4"><AlertTriangle className="h-4 w-4 text-amber-500"/><p className="mt-2 text-xs text-ink-500">Dispute history</p><p className="mt-1 font-semibold text-ink-100">{inspection.seller.dispute_rate}% dispute rate</p></div><div className="rounded-xl bg-base-800 p-4"><ShieldCheck className="h-4 w-4 text-violet-500"/><p className="mt-2 text-xs text-ink-500">Seller trust index</p><p className="mt-1 font-semibold text-ink-100">{inspection.seller.trust_index}</p></div></div>}{tab === "price" && <PriceGraph inspection={inspection}/>} {tab === "sentiment" && <div className="grid place-items-center py-6 text-center"><BarChart3 className="h-8 w-8 text-astra-violet"/><p className="mt-3 font-display text-4xl font-bold text-ink-100">{inspection.review_sentiment_score}</p><p className={`mt-2 rounded-full px-3 py-1 text-xs font-semibold ${inspection.authenticity_flag ? "bg-rose-500/10 text-rose-500" : "bg-emerald-500/10 text-emerald-500"}`}>{inspection.authenticity_flag ? "Suspicious/fake review signals detected" : "Review patterns passed authenticity scan"}</p><p className="mt-3 max-w-md text-xs leading-5 text-ink-500">{inspection.reasoning_summary}</p></div>}</div></section></div> : <section className="glass grid min-h-72 place-items-center rounded-xl2 p-8 text-center"><div><ShieldCheck className="mx-auto h-10 w-10 text-ink-500"/><p className="mt-3 text-sm font-semibold text-ink-100">Run an inspection to view live trust intelligence</p></div></section>}
    <section className="glass rounded-xl2 p-5"><h2 className="text-sm font-semibold text-ink-100">Admin / Verification Actions</h2><p className="mt-1 text-xs text-ink-500">Every action is persisted with actor, reason, previous score, and final score.</p><label className="mt-4 block text-[10px] font-semibold uppercase tracking-wide text-ink-500">Audit reason</label><input value={actionReason} onChange={(e) => setActionReason(e.target.value)} maxLength={500} className="mt-2 w-full rounded-lg border border-base-600 bg-base-800 px-3 py-2.5 text-xs text-ink-100 outline-none focus:border-astra-indigo" placeholder="Required reason for the audit trail"/><div className="mt-3 grid gap-3 lg:grid-cols-[190px_1fr_1fr]"><div className="flex gap-2"><input aria-label="Manual trust score" type="number" min="0" max="100" value={overrideScore} onChange={(e) => setOverrideScore(e.target.value)} className="w-20 rounded-lg border border-base-600 bg-base-800 px-3 text-xs text-ink-100"/><button type="button" disabled={!inspection || busy || !actionReason.trim()} onClick={() => void action("manual_override")} className="rounded-lg border border-amber-500/30 px-3 py-2 text-xs font-semibold text-amber-500 disabled:cursor-not-allowed disabled:opacity-40">Override</button></div><button type="button" disabled={!inspection || busy || !actionReason.trim()} onClick={() => void action("flagged")} className="rounded-lg border border-rose-500/30 px-4 py-3 text-xs font-semibold text-rose-500 disabled:cursor-not-allowed disabled:opacity-40"><Flag className="mr-2 inline h-4 w-4"/>Flag Listing for Audit</button><button type="button" disabled={!inspection || busy || !actionReason.trim()} onClick={() => void action("approved_for_deals")} className="rounded-lg bg-astra-gradient px-4 py-3 text-xs font-semibold text-white disabled:cursor-not-allowed disabled:opacity-40"><CheckCircle2 className="mr-2 inline h-4 w-4"/>Approve for Deals Page Push</button></div></section>
  </div>;
}
