"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { AlertTriangle, Check, Loader2, Undo2 } from "lucide-react";
import FinancialConsentModal from "@/components/FinancialConsentModal";
import { approveOrder, cancelOrder } from "@/lib/api";
import type { ApprovalStatusOut } from "@/lib/types";

export default function HumanApprovalWidget({ approval }: { approval: ApprovalStatusOut | null }) {
  const [secondsLeft, setSecondsLeft] = useState(approval?.seconds_left ?? 0); const [resolved, setResolved] = useState<"pending" | "approved" | "cancelled">("pending"); const [busy, setBusy] = useState(false); const [consentOpen, setConsentOpen] = useState(false); const [error, setError] = useState("");
  useEffect(() => { setSecondsLeft(approval?.seconds_left ?? 0); setResolved("pending"); }, [approval?.order_ref, approval?.seconds_left]);
  useEffect(() => { if (!approval || resolved !== "pending" || secondsLeft <= 0) return; const timer = setTimeout(() => setSecondsLeft((value) => value - 1), 1000); return () => clearTimeout(timer); }, [approval, resolved, secondsLeft]);
  if (!approval) return <section className="glass glass-hover rounded-xl2 border-signal-hold/20 p-5"><div className="mb-2 flex items-center gap-2"><AlertTriangle className="h-3.5 w-3.5 text-ink-500" /><h2 className="font-display text-sm font-semibold text-ink-100">Human Approval</h2></div><p className="text-xs text-ink-500">No order is currently waiting for your approval.</p></section>;
  const progress = Math.max(0, Math.min(100, secondsLeft / approval.window_seconds * 100));
  async function approve(consentId?: string) { setBusy(true); setError(""); try { await approveOrder(approval!.order_ref, consentId); setResolved("approved"); setConsentOpen(false); } catch (cause) { const message = cause instanceof Error ? cause.message : "Approval failed"; if (message.includes("FINANCIAL_CONSENT_REQUIRED")) setConsentOpen(true); else setError(message); } finally { setBusy(false); } }
  async function cancel() { setBusy(true); setError(""); try { await cancelOrder(approval!.order_ref); setResolved("cancelled"); } catch (cause) { setError(cause instanceof Error ? cause.message : "Cancellation failed"); } finally { setBusy(false); } }
  return <><section className="glass glass-hover rounded-xl2 border-signal-hold/20 p-5"><div className="mb-3 flex items-center gap-2"><AlertTriangle className="h-3.5 w-3.5 text-signal-hold" /><h2 className="font-display text-sm font-semibold text-ink-100">Human Approval Required</h2></div>{resolved === "pending" ? <><p className="mb-3 text-xs text-ink-300">{approval.prompt_text}</p><p className="mb-4 font-display text-sm font-bold text-ink-100">Rs. {approval.amount.toLocaleString()}</p>{error && <p className="mb-3 rounded-lg bg-signal-reject/10 p-2 text-[10px] text-signal-reject">{error}</p>}<div className="relative mx-auto grid h-24 w-24 place-items-center"><svg className="absolute inset-0 -rotate-90" viewBox="0 0 100 100"><circle cx="50" cy="50" r="44" fill="none" stroke="rgb(var(--base-600))" strokeWidth="6" /><circle cx="50" cy="50" r="44" fill="none" stroke="#8b5cf6" strokeWidth="6" strokeLinecap="round" strokeDasharray={2 * Math.PI * 44} strokeDashoffset={2 * Math.PI * 44 * (1 - progress / 100)} className="transition-all duration-1000" /></svg><div className="text-center"><p className="font-display text-2xl font-bold text-ink-100">{secondsLeft}</p><p className="text-[10px] text-ink-500">seconds</p></div></div><button onClick={() => void approve()} disabled={busy || secondsLeft <= 0} className="mt-5 flex w-full items-center justify-center gap-2 rounded-lg bg-astra-gradient py-2.5 text-xs font-semibold text-white shadow-glow disabled:opacity-60">{busy ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Check className="h-3.5 w-3.5" />} Approve Transaction</button><button onClick={() => void cancel()} disabled={busy} className="mt-2 flex w-full items-center justify-center gap-2 rounded-lg border border-base-600 py-2.5 text-xs font-medium text-ink-300 hover:text-signal-reject disabled:opacity-60"><Undo2 className="h-3.5 w-3.5" /> Cancel & Refund</button></> : <div className="grid place-items-center gap-3 py-8 text-center"><span className={`grid h-12 w-12 place-items-center rounded-full ${resolved === "approved" ? "bg-signal-good/10" : "bg-signal-reject/10"}`}>{resolved === "approved" ? <Check className="h-5 w-5 text-signal-good" /> : <Undo2 className="h-5 w-5 text-signal-reject" />}</span><p className="text-xs font-medium text-ink-100">{resolved === "approved" ? "Transaction approved" : "Order cancelled — refund started"}</p><Link href="/orders" className="text-[11px] text-ink-500 hover:text-ink-100">View in Orders →</Link></div>}</section><FinancialConsentModal open={consentOpen} amount={approval.amount} orderRef={approval.order_ref} onClose={() => setConsentOpen(false)} onAuthorized={(consentId) => approve(consentId)} /></>;
}
