"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { CheckCircle2, ChevronLeft, Heart, Loader2, Minus, Plus, ShieldCheck, ShoppingCart, Star, Tags, Wallet2, ZoomIn } from "lucide-react";
import FinancialConsentModal from "@/components/FinancialConsentModal";
import { addToCart, checkoutCart, createShoppingGoal, getDealsWebSocketUrl, getProduct, updateShoppingGoal } from "@/lib/api";
import type { ProductDetail } from "@/lib/types";

export default function ProductDetailClient({ initialProduct }: { initialProduct: ProductDetail }) {
  const [product, setProduct] = useState(initialProduct); const [image, setImage] = useState(initialProduct.images[0] ?? initialProduct.image ?? "");
  const [color, setColor] = useState(initialProduct.variants.colors[0] ?? ""); const [size, setSize] = useState(initialProduct.variants.sizes[0] ?? ""); const [storage, setStorage] = useState(initialProduct.variants.storage[0] ?? "");
  const [quantity, setQuantity] = useState(1); const [zoom, setZoom] = useState(false); const [busy, setBusy] = useState<"cart"|"buy"|"goal"|null>(null); const [notice, setNotice] = useState(""); const [error, setError] = useState("");
  const [consentOpen, setConsentOpen] = useState(false); const [checkoutRef, setCheckoutRef] = useState(""); const [address, setAddress] = useState(""); const [goalOpen, setGoalOpen] = useState(false); const [goalDeposit, setGoalDeposit] = useState("");
  useEffect(() => { const socket = new WebSocket(getDealsWebSocketUrl()); socket.onmessage = (event) => { try { const payload = JSON.parse(event.data) as { product_id?: string; type?: string }; if (!payload.product_id || payload.product_id === product.slug) void getProduct(product.slug).then(setProduct); } catch {} }; return () => socket.close(); }, [product.slug]);
  const selection = { color, size, storage };
  async function add() { setBusy("cart"); setError(""); try { const result = await addToCart(product.slug, quantity, selection); setNotice(result.message); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not add to cart"); } finally { setBusy(null); } }
  async function buy(consentId?: string) { if (address.trim().length < 8) { setError("Enter a complete shipping address before Buy Now."); return; } setBusy("buy"); setError(""); try { if (!consentId) await addToCart(product.slug, quantity, selection); const result = await checkoutCart({ shipping_address: address, consent_id: consentId }); setConsentOpen(false); setNotice(`Order placed: ${result.order_refs.join(", ")}`); } catch (cause) { const message = cause instanceof Error ? cause.message : "Checkout failed"; if (message.includes("FINANCIAL_CONSENT_REQUIRED")) { setCheckoutRef(message.split(":").pop() ?? "CART-CHECKOUT"); setConsentOpen(true); } else setError(message); } finally { setBusy(null); } }
  async function saveGoal() { setBusy("goal"); setError(""); try { const goal = await createShoppingGoal({ target_title: product.name, target_price: product.price * quantity, category: product.category, priority_level: "High" }); const deposit = Number(goalDeposit); if (deposit > 0) await updateShoppingGoal(goal.goal_id, { deposit_amount: deposit }); setGoalOpen(false); setNotice("Shopping goal created and allocation saved."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Goal could not be created"); } finally { setBusy(null); } }
  return <><Link href="/explore" className="flex items-center gap-1 text-[11px] font-medium text-ink-500 hover:text-ink-100"><ChevronLeft className="h-3.5 w-3.5" /> Back to Explore</Link>
    <div className="grid gap-6 lg:grid-cols-[minmax(0,500px)_1fr]"><section><button onClick={() => setZoom(true)} className="group relative aspect-square w-full overflow-hidden rounded-3xl bg-base-900"><img src={image} alt={product.name} className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /><span className="absolute bottom-4 right-4 rounded-full bg-slate-950/70 p-3 text-white"><ZoomIn className="h-4 w-4" /></span></button><div className="mt-3 flex gap-2 overflow-x-auto">{product.images.map((item) => <button key={item} onClick={() => setImage(item)} className={`h-20 w-20 shrink-0 overflow-hidden rounded-xl border ${image === item ? "border-violet-400" : "border-base-600"}`}><img src={item} alt="Product view" className="h-full w-full object-cover" /></button>)}</div></section>
    <div className="space-y-5"><section className="glass rounded-xl2 p-5"><div className="flex flex-wrap items-center gap-2">{product.tag && <span className="rounded-full bg-astra-gradient px-3 py-1 text-[10px] font-bold text-white">{product.tag}</span>}<span className="flex items-center gap-1 text-xs text-emerald-400"><ShieldCheck className="h-4 w-4" /> {product.trust}% live trust</span><span className="text-xs text-ink-500">{product.stock_count} in stock</span></div><h1 className="mt-3 font-display text-2xl font-bold text-ink-100">{product.name}</h1><p className="mt-2 text-sm text-ink-500">{product.description}</p><p className="mt-4 font-display text-3xl font-bold text-ink-100">{product.price_display}</p>
      {([['Color', product.variants.colors, color, setColor], ['Size', product.variants.sizes, size, setSize], ['Storage', product.variants.storage, storage, setStorage]] as const).map(([label, options, selected, setter]) => options.length > 0 && <div key={label} className="mt-4"><p className="mb-2 text-[10px] font-bold uppercase tracking-wider text-ink-500">{label}</p><div className="flex flex-wrap gap-2">{options.map((option) => <button key={option} onClick={() => setter(option)} className={`rounded-xl border px-3 py-2 text-xs ${selected === option ? "border-violet-400 bg-violet-500/10 text-white" : "border-base-600 text-ink-500"}`}>{option}</button>)}</div></div>)}
      <div className="mt-4 flex items-center gap-3"><button onClick={() => setQuantity((value) => Math.max(1, value-1))} className="rounded-lg border border-base-600 p-2"><Minus className="h-3 w-3" /></button><span className="text-sm text-ink-100">{quantity}</span><button onClick={() => setQuantity((value) => Math.min(product.stock_count, value+1))} className="rounded-lg border border-base-600 p-2"><Plus className="h-3 w-3" /></button></div>
      <input value={address} onChange={(event) => setAddress(event.target.value)} placeholder="Shipping address for Buy Now" className="mt-4 w-full rounded-xl border border-base-600 bg-base-900 px-4 py-3 text-xs text-ink-100" />
      <div className="mt-4 grid gap-2 sm:grid-cols-2"><button onClick={() => void add()} disabled={busy !== null} className="flex items-center justify-center gap-2 rounded-xl border border-violet-400/40 py-3 text-xs font-bold text-white">{busy === "cart" ? <Loader2 className="h-4 w-4 animate-spin" /> : <ShoppingCart className="h-4 w-4" />} Add to Cart</button><button onClick={() => void buy()} disabled={busy !== null || product.stock_count < 1} className="rounded-xl bg-astra-gradient py-3 text-xs font-bold text-white">{busy === "buy" ? "Processing…" : "Buy Now"}</button></div><button onClick={() => setGoalOpen(true)} className="mt-2 flex w-full items-center justify-center gap-2 rounded-xl bg-base-800 py-3 text-xs font-semibold text-ink-300"><Heart className="h-4 w-4" /> Save to Shopping Goal</button>{notice && <p className="mt-3 text-xs text-emerald-400">{notice}</p>}{error && <p className="mt-3 text-xs text-rose-400">{error}</p>}</section>
      <section className="glass rounded-xl2 p-5"><h2 className="font-display text-sm font-bold text-ink-100">ASTRA Check & buyer reviews</h2><div className="mt-4 grid gap-3 sm:grid-cols-3">{[{icon:Wallet2,label:"Financial Fit",value:product.fit},{icon:ShieldCheck,label:"Seller Trust",value:`${product.trust}% verified`},{icon:Tags,label:"Review Sentiment",value:`${product.sentiment.positive}% positive`}].map(({icon:Icon,label,value})=><div key={label} className="rounded-xl bg-base-900 p-3"><Icon className="h-4 w-4 text-cyan-400"/><p className="mt-2 text-xs font-semibold text-white">{label}</p><p className="text-[10px] text-ink-500">{value}</p></div>)}</div><div className="mt-5 grid gap-5 md:grid-cols-2"><div>{Object.entries(product.rating_breakdown).reverse().map(([rating,count])=><div key={rating} className="mb-2 flex items-center gap-2 text-[10px] text-ink-500"><span>{rating}★</span><div className="h-1.5 flex-1 overflow-hidden rounded bg-base-700"><div className="h-full bg-amber-400" style={{width:`${product.total_reviews ? count/product.total_reviews*100 : 0}%`}}/></div><span>{count}</span></div>)}</div><div>{product.reviews.map((review)=><article key={review.id} className="rounded-xl bg-base-900 p-3"><p className="flex items-center gap-2 text-xs font-semibold text-white">{review.buyer}{review.verified&&<CheckCircle2 className="h-3 w-3 text-emerald-400"/>}</p><p className="mt-1 text-amber-400">{Array.from({length:review.rating}).map((_,i)=><Star key={i} className="inline h-3 w-3 fill-current"/>)}</p><p className="mt-2 text-xs text-ink-500">{review.comment}</p></article>)}</div></div></section>
    </div></div>
    {zoom && <button onClick={() => setZoom(false)} className="fixed inset-0 z-[80] grid place-items-center bg-slate-950/90 p-6"><img src={image} alt={product.name} className="max-h-full max-w-full rounded-3xl object-contain" /></button>}
    {goalOpen && <div className="fixed inset-0 z-[85] grid place-items-center bg-slate-950/75 p-4"><section className="glass w-full max-w-md rounded-3xl p-6"><h2 className="font-display text-lg font-bold text-white">Save to Shopping Goal</h2><p className="mt-2 text-xs text-ink-500">Target: Rs. {(product.price*quantity).toLocaleString()}</p><input type="number" min="0" value={goalDeposit} onChange={(e)=>setGoalDeposit(e.target.value)} placeholder="Initial allocation (optional)" className="mt-4 w-full rounded-xl border border-base-600 bg-base-900 px-4 py-3 text-xs text-white"/><div className="mt-4 grid grid-cols-2 gap-2"><button onClick={()=>void saveGoal()} className="rounded-xl bg-astra-gradient py-3 text-xs font-bold text-white">Save Goal</button><button onClick={()=>setGoalOpen(false)} className="rounded-xl border border-base-600 text-xs text-ink-300">Cancel</button></div></section></div>}
    <FinancialConsentModal open={consentOpen} amount={product.price*quantity} orderRef={checkoutRef} onClose={()=>setConsentOpen(false)} onAuthorized={async(id)=>{await buy(id);}} />
  </>;
}
