from typing import Any

from app.models.explore import ProductModel


def _image(keywords: str) -> str:
    images = {
        "smartphone,samsung": "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=600&q=80",
        "laptop,lenovo": "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=600&q=80",
        "headphones,sony": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80",
        "smartwatch,applewatch": "https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=600&q=80",
        "smartphone,xiaomi": "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=600&q=80",
        "laptop,dell": "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=600&q=80",
        "headphones,wireless": "https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=600&q=80",
        "earrings,goldjewelry": "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=600&q=80",
        "embroidery,fabric": "https://images.unsplash.com/photo-1598033129183-c4f50c736f10?auto=format&fit=crop&w=600&q=80",
        "lipstick,cosmetics": "https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=600&q=80",
        "kitchenappliance": "https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=600&q=80",
    }
    return images.get(keywords, "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=600&q=80")


# Replace this in-memory repository with a PostgreSQL/pgvector or Elasticsearch adapter.
PRODUCTS: list[ProductModel] = [
    {
        "id": "samsung-galaxy-s25-ultra",
        "title": "Samsung Galaxy S25 Ultra",
        "category": "Mobiles",
        "price": 314999.0,
        "rating": 4.8,
        "total_reviews": 1240,
        "seller_name": "TechBazaar Official",
        "is_verified_seller": True,
        "badge": "Bestseller",
        "image_url": _image("smartphone,samsung"),
        "semantic_tags": ["Fits your budget", "Bestseller", "Verified seller", "Fast delivery", "Highly rated"],
        "description": "Flagship Android phone with a 200MP camera system, titanium frame, and on-device AI features.",
        "fit": "Fits your budget",
        "trust": 96,
        "search_terms": "samsung galaxy s25 ultra flagship android phone camera gaming mobile",
    },
    {
        "id": "lenovo-ideapad-slim-5",
        "title": "Lenovo IdeaPad Slim 5",
        "category": "Laptops & Computers",
        "price": 149999.0,
        "rating": 4.5,
        "total_reviews": 468,
        "seller_name": "LaptopHub PK",
        "is_verified_seller": True,
        "badge": None,
        "image_url": _image("laptop,lenovo"),
        "semantic_tags": ["Fits your budget", "Verified seller", "Fast delivery", "Eco-friendly"],
        "description": "A lightweight everyday laptop with Ryzen 5, 16GB RAM, and a 512GB SSD.",
        "fit": "Fits your budget",
        "trust": 91,
        "search_terms": "lenovo ideapad slim 5 laptop computer gaming laptop ryzen ram ssd",
    },
    {
        "id": "sony-wh-1000xm5",
        "title": "Sony WH-1000XM5",
        "category": "Audio & Wearables",
        "price": 59999.0,
        "rating": 4.9,
        "total_reviews": 892,
        "seller_name": "AudioNest",
        "is_verified_seller": True,
        "badge": None,
        "image_url": _image("headphones,sony"),
        "semantic_tags": ["Verified seller", "Highly rated"],
        "description": "Industry-leading noise cancelling headphones with clear wireless audio.",
        "fit": "Stretch (Manageable)",
        "trust": 88,
        "search_terms": "sony wh 1000xm5 headphones audio wireless noise cancelling",
    },
    {
        "id": "apple-watch-series-9",
        "title": "Apple Watch Series 9",
        "category": "Audio & Wearables",
        "price": 134999.0,
        "rating": 4.6,
        "total_reviews": 611,
        "seller_name": "iStore Lahore",
        "is_verified_seller": True,
        "badge": None,
        "image_url": _image("smartwatch,applewatch"),
        "semantic_tags": ["Fits your budget", "Verified seller", "Fast delivery"],
        "description": "Health and fitness tracking with a bright always-on display.",
        "fit": "Fits your budget",
        "trust": 94,
        "search_terms": "apple watch series 9 smartwatch wearable health fitness",
    },
    {
        "id": "xiaomi-14-civi",
        "title": "Xiaomi 14 Civi",
        "category": "Mobiles",
        "price": 124999.0,
        "rating": 4.3,
        "total_reviews": 209,
        "seller_name": "MobileWorld",
        "is_verified_seller": False,
        "badge": "New",
        "image_url": _image("smartphone,xiaomi"),
        "semantic_tags": ["Fits your budget", "New", "Eco-friendly"],
        "description": "A camera-focused mid-flagship smartphone with a compact design.",
        "fit": "Fits your budget",
        "trust": 82,
        "search_terms": "xiaomi 14 civi smartphone mobile camera phone",
    },
    {
        "id": "dell-xps-13",
        "title": "Dell XPS 13",
        "category": "Laptops & Computers",
        "price": 289999.0,
        "rating": 4.7,
        "total_reviews": 377,
        "seller_name": "ComputerCity",
        "is_verified_seller": True,
        "badge": None,
        "image_url": _image("laptop,dell"),
        "semantic_tags": ["Verified seller", "Highly rated"],
        "description": "Premium ultrabook with an InfinityEdge display.",
        "fit": "Stretch (Manageable)",
        "trust": 93,
        "search_terms": "dell xps 13 laptop computer ultrabook premium",
    },
    {
        "id": "anker-soundcore-q45",
        "title": "Anker Soundcore Q45",
        "category": "Audio & Wearables",
        "price": 24999.0,
        "rating": 4.4,
        "total_reviews": 531,
        "seller_name": "GadgetVault",
        "is_verified_seller": False,
        "badge": "Deal",
        "image_url": _image("headphones,wireless"),
        "semantic_tags": ["Fits your budget", "Deal", "Fast delivery"],
        "description": "Budget noise-cancelling headphones priced below the market average.",
        "fit": "Fits your budget",
        "trust": 85,
        "search_terms": "anker soundcore q45 headphones audio wireless noise cancelling",
    },
    {
        "id": "gold-plated-jhumka-earrings",
        "title": "Gold-Plated Jhumka Earrings",
        "category": "Jewelry",
        "price": 8499.0,
        "rating": 4.6,
        "total_reviews": 318,
        "seller_name": "Zeenat Jewels",
        "is_verified_seller": True,
        "badge": "Bestseller",
        "image_url": _image("earrings,goldjewelry"),
        "semantic_tags": ["Fits your budget", "Bestseller", "Verified seller", "Handcrafted"],
        "description": "Handcrafted gold-plated jhumkas with an antique finish.",
        "fit": "Fits your budget",
        "trust": 90,
        "search_terms": "gold plated jhumka earrings jewelry handcrafted",
    },
    {
        "id": "embroidered-lawn-3pc-suit",
        "title": "Embroidered Lawn 3-Piece Suit",
        "category": "Clothing & Fashion",
        "price": 6990.0,
        "rating": 4.4,
        "total_reviews": 276,
        "seller_name": "Threads & Co.",
        "is_verified_seller": True,
        "badge": "New",
        "image_url": _image("embroidery,fabric"),
        "semantic_tags": ["Fits your budget", "New", "Seasonal"],
        "description": "Unstitched lawn three-piece with digital print and an embroidered neckline.",
        "fit": "Fits your budget",
        "trust": 87,
        "search_terms": "embroidered lawn 3 piece suit clothing fashion",
    },
    {
        "id": "matte-liquid-lipstick-set",
        "title": "Matte Liquid Lipstick Set (6-Pack)",
        "category": "Makeup & Beauty",
        "price": 3299.0,
        "rating": 4.5,
        "total_reviews": 442,
        "seller_name": "GlowBox Cosmetics",
        "is_verified_seller": False,
        "badge": "Deal",
        "image_url": _image("lipstick,cosmetics"),
        "semantic_tags": ["Fits your budget", "Deal", "Long wear"],
        "description": "Long-wear matte finish in six everyday shades, priced below comparable sets.",
        "fit": "Fits your budget",
        "trust": 84,
        "search_terms": "matte liquid lipstick set makeup beauty cosmetics",
    },
    {
        "id": "air-fryer-digital-5l",
        "title": "Digital Air Fryer 5L",
        "category": "Home Appliances",
        "price": 28999.0,
        "rating": 4.3,
        "total_reviews": 194,
        "seller_name": "HomeTech PK",
        "is_verified_seller": True,
        "badge": None,
        "image_url": _image("kitchenappliance"),
        "semantic_tags": ["Fits your budget", "Verified seller", "Energy efficient"],
        "description": "A five-litre digital air fryer with preset cooking modes.",
        "fit": "Fits your budget",
        "trust": 89,
        "search_terms": "digital air fryer home appliance kitchen",
    },
]
